# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormatConvertTools.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 715)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1181, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(200, 10, 581, 621))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.command_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.command_groupBox.setEnabled(False)
        self.command_groupBox.setGeometry(QtCore.QRect(10, 490, 561, 121))
        self.command_groupBox.setObjectName("command_groupBox")
        self.command_comboBox = QtWidgets.QComboBox(self.command_groupBox)
        self.command_comboBox.setGeometry(QtCore.QRect(9, 20, 461, 20))
        self.command_comboBox.setEditable(True)
        self.command_comboBox.setObjectName("command_comboBox")
        self.send_pushButton = QtWidgets.QPushButton(self.command_groupBox)
        self.send_pushButton.setGeometry(QtCore.QRect(480, 20, 75, 23))
        self.send_pushButton.setObjectName("send_pushButton")
        self.all_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.all_groupBox.setEnabled(False)
        self.all_groupBox.setGeometry(QtCore.QRect(10, 10, 561, 281))
        self.all_groupBox.setObjectName("all_groupBox")
        self.all_tableWidget = QtWidgets.QTableWidget(self.all_groupBox)
        self.all_tableWidget.setGeometry(QtCore.QRect(10, 20, 541, 251))
        self.all_tableWidget.setMaximumSize(QtCore.QSize(1000, 300))
        self.all_tableWidget.setColumnCount(0)
        self.all_tableWidget.setObjectName("all_tableWidget")
        self.all_tableWidget.setRowCount(0)
        self.error_groupBox = QtWidgets.QGroupBox(self.groupBox)
        self.error_groupBox.setEnabled(False)
        self.error_groupBox.setGeometry(QtCore.QRect(10, 300, 561, 181))
        self.error_groupBox.setObjectName("error_groupBox")
        self.error_tableWidget = QtWidgets.QTableWidget(self.error_groupBox)
        self.error_tableWidget.setGeometry(QtCore.QRect(10, 20, 541, 151))
        self.error_tableWidget.setObjectName("error_tableWidget")
        self.error_tableWidget.setColumnCount(0)
        self.error_tableWidget.setRowCount(0)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 181, 621))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.control_groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.control_groupBox.setGeometry(QtCore.QRect(10, 10, 161, 301))
        self.control_groupBox.setObjectName("control_groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.control_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 141, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startApp_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startApp_pushButton.setObjectName("startApp_pushButton")
        self.verticalLayout_2.addWidget(self.startApp_pushButton)
        self.closeApp_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.closeApp_pushButton.setEnabled(False)
        self.closeApp_pushButton.setObjectName("closeApp_pushButton")
        self.verticalLayout_2.addWidget(self.closeApp_pushButton)
        self.start_format_convert_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.start_format_convert_pushButton.setEnabled(False)
        self.start_format_convert_pushButton.setObjectName("start_format_convert_pushButton")
        self.verticalLayout_2.addWidget(self.start_format_convert_pushButton)
        self.stop_format_convert_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_format_convert_pushButton.setEnabled(False)
        self.stop_format_convert_pushButton.setObjectName("stop_format_convert_pushButton")
        self.verticalLayout_2.addWidget(self.stop_format_convert_pushButton)
        self.format_groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.format_groupBox.setEnabled(False)
        self.format_groupBox.setGeometry(QtCore.QRect(10, 320, 161, 291))
        self.format_groupBox.setObjectName("format_groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.format_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 141, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.orignal_label = QtWidgets.QLabel(self.layoutWidget1)
        self.orignal_label.setObjectName("orignal_label")
        self.horizontalLayout_3.addWidget(self.orignal_label)
        self.orignal_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.orignal_comboBox.setObjectName("orignal_comboBox")
        self.orignal_comboBox.addItem("")
        self.orignal_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.orignal_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.target_label = QtWidgets.QLabel(self.layoutWidget1)
        self.target_label.setObjectName("target_label")
        self.horizontalLayout_2.addWidget(self.target_label)
        self.target_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.target_comboBox.setObjectName("target_comboBox")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.target_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folder_label = QtWidgets.QLabel(self.layoutWidget1)
        self.folder_label.setObjectName("folder_label")
        self.horizontalLayout.addWidget(self.folder_label)
        self.folder_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.folder_lineEdit.setObjectName("folder_lineEdit")
        self.horizontalLayout.addWidget(self.folder_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.folder_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.folder_pushButton.setObjectName("folder_pushButton")
        self.verticalLayout.addWidget(self.folder_pushButton)
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(780, 10, 391, 621))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.target_comboBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "格式转换工具"))
        self.command_groupBox.setTitle(_translate("MainWindow", "命令控制"))
        self.send_pushButton.setText(_translate("MainWindow", "发送"))
        self.all_groupBox.setTitle(_translate("MainWindow", "全部文件"))
        self.error_groupBox.setTitle(_translate("MainWindow", "错误文件"))
        self.control_groupBox.setTitle(_translate("MainWindow", "控制"))
        self.startApp_pushButton.setText(_translate("MainWindow", "启动程序"))
        self.closeApp_pushButton.setText(_translate("MainWindow", "关闭程序"))
        self.start_format_convert_pushButton.setText(_translate("MainWindow", "开始转换"))
        self.stop_format_convert_pushButton.setText(_translate("MainWindow", "停止转换"))
        self.format_groupBox.setTitle(_translate("MainWindow", "格式"))
        self.orignal_label.setText(_translate("MainWindow", "源格式："))
        self.orignal_comboBox.setItemText(0, _translate("MainWindow", "*.img"))
        self.orignal_comboBox.setItemText(1, _translate("MainWindow", "*.tif"))
        self.target_label.setText(_translate("MainWindow", "目标格式："))
        self.target_comboBox.setItemText(0, _translate("MainWindow", "*.img"))
        self.target_comboBox.setItemText(1, _translate("MainWindow", "*.tif"))
        self.target_comboBox.setItemText(2, _translate("MainWindow", "*.tiff"))
        self.target_comboBox.setItemText(3, _translate("MainWindow", "*.dat"))
        self.target_comboBox.setItemText(4, _translate("MainWindow", "*.dac"))
        self.target_comboBox.setItemText(5, _translate("MainWindow", "*.data2tiff"))
        self.target_comboBox.setItemText(6, _translate("MainWindow", "*.data2tif"))
        self.target_comboBox.setItemText(7, _translate("MainWindow", "*.display2tiff"))
        self.target_comboBox.setItemText(8, _translate("MainWindow", "*.display2tif"))
        self.folder_label.setText(_translate("MainWindow", "文件夹："))
        self.folder_pushButton.setText(_translate("MainWindow", "选择"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "条纹相机"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


